### ISSUE TITLE
[Bug]: RangeError: Set maximum size exceeded

### ISSUE THREAD

**Issue by vulevukusej** [IFCjs/components#206]
### What happened?

Loading a file on https://platform.thatopen.com/app and i receive the error below.

### Version

latest

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
Uncaught (in promise) RangeError: Set maximum size exceeded
    at Set.add (<anonymous>)
    at aG.getAllGeometriesIDs (9249.a39bde93b4db5cf6.js:6:393264)
    at async aG.export (9249.a39bde93b4db5cf6.js:6:392019)
```

### Anything else?

Model has been sent to antonio@thatopen.com

**Comment by agviegas** [comment]
Probably a cause for this issue is that we are loading everything in memory at the same time, which is not very scalable. Hopefully with the BIM tiles approach, which is around the corner, this will be solved.

**Comment by davidgtl** [comment]
> Probably a cause for this issue is that we are loading everything in memory at the same time, which is not very scalable. Hopefully with the BIM tiles approach, which is around the corner, this will be solved.

Chunking the geometry ids across multiple <16M sets would indeed fix this. I'm excited to see what BIM tiles can do!

Until then, a workaround like the try catch I mentioned would be very useful to be able to notify the user that properties couldn't be loaded instead of waiting for them forever.

**Comment by HoyosJuan** [comment]
Yes @davidgtl, I see why not adding the try/catch statement as a workaround for now. Will let you know when it's done.
